### ISSUE TITLE
coil creator makes incorrect spacings

### ISSUE THREAD

**Issue by geoskd** [spoter368/kicad-coil-creator#3]
Using the following settings:
NAME = "iso_coil"  # Name of footprint
DUAL_LAYER = True  # Determines if bottom layer should be used or not
WRAP_CLOCKWISE = True  # Wraps CCW if false
N_TURNS = 12  # Must be an int, per layer
TRACE_WIDTH = 0.7  # (mm)
TRACE_SPACING = 0.127  # (mm)
VIA_DIAMETER = 0.6  # (mm)
VIA_DRILL = 0.3  # (mm)
VIA_OFFSET = 0  # (mm)
BREAKOUT_LEN = 0.5  # (mm) scalar used to affect location of the breakouts
TEMPLATE_FILE = "template.kicad_mod"
TOP_LAYER = "F.Cu"
BOTTOM_LAYER = "B.Cu"

The spacings should all be 0.127mm, but spacing near the center of the coil are distorted and smaller than they should be. Some as small as 0.05mm.

I noticed that the coils are not using perfect 180 degree arcs, which may be the problem.

**Comment by spoter368** [comment]
Just pushed a fix, nice catch! Let me know if it works for you. If not, feel free to reopen

**Comment by geoskd** [comment]
> Just pushed a fix, nice catch! Let me know if it works for you. If not, feel free to reopen

Looks Good! I've built a bunch of test coils today, and so far every one has checked out.
